### ISSUE TITLE
Customize Embed

### ISSUE THREAD

**Issue by andrewc2** [Lucxjo/reddit-discord-bridge#7]
If I wanted to customize the embed it appears that `sendToWebhook.ts` needs to be updated. What would I need to bind my path to, in order to swap it?

**Comment by Lucxjo** [comment]
The best way currently would be to clone the project, change the value in the webhook file and rebuild. I can look into implementing something on Thursday or Friday this week to make it simpler

**Comment by andrewc2** [comment]
I'll give it a try, docker is still half wizardry to me 😂, if you're able to implement a way to do it "natively" that would be great. I'll keep an eye out, thanks.

**Comment by Lucxjo** [comment]
This has now been added to the project. You can see a configuration example in the /data/config.json file or at https://rdb.ludoviko.ch/#configuration. I will be doing more work to the project in the future so please be aware that the configuration options may change soon when v2 is ready.

Thanks for the suggestion 🙂
